on: [push]

jobs:
  send_gif_job:
    runs-on: ubuntu-latest
    name: Sends Gif
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout
      - name: Sends gif
        run: echo "Gif ${{ steps.hello.outputs.gif }}"